// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.fnic.dhc.domain;

import cn.fnic.dhc.domain.AdminUserDataOnDemand;
import cn.fnic.dhc.domain.AdminUserIntegrationTest;
import cn.fnic.dhc.repository.AdminUserRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AdminUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AdminUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AdminUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AdminUserIntegrationTest: @Transactional;
    
    @Autowired
    AdminUserDataOnDemand AdminUserIntegrationTest.dod;
    
    @Autowired
    AdminUserRepository AdminUserIntegrationTest.adminUserRepository;
    
    @Test
    public void AdminUserIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to initialize correctly", dod.getRandomAdminUser());
        long count = adminUserRepository.count();
        Assert.assertTrue("Counter for 'AdminUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AdminUserIntegrationTest.testFind() {
        AdminUser obj = dod.getRandomAdminUser();
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to provide an identifier", id);
        obj = adminUserRepository.findOne(id);
        Assert.assertNotNull("Find method for 'AdminUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AdminUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AdminUserIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to initialize correctly", dod.getRandomAdminUser());
        long count = adminUserRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'AdminUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AdminUser> result = adminUserRepository.findAll();
        Assert.assertNotNull("Find all method for 'AdminUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AdminUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AdminUserIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to initialize correctly", dod.getRandomAdminUser());
        long count = adminUserRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AdminUser> result = adminUserRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'AdminUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AdminUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AdminUserIntegrationTest.testFlush() {
        AdminUser obj = dod.getRandomAdminUser();
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to provide an identifier", id);
        obj = adminUserRepository.findOne(id);
        Assert.assertNotNull("Find method for 'AdminUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAdminUser(obj);
        Integer currentVersion = obj.getVersion();
        adminUserRepository.flush();
        Assert.assertTrue("Version for 'AdminUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdminUserIntegrationTest.testSaveUpdate() {
        AdminUser obj = dod.getRandomAdminUser();
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to provide an identifier", id);
        obj = adminUserRepository.findOne(id);
        boolean modified =  dod.modifyAdminUser(obj);
        Integer currentVersion = obj.getVersion();
        AdminUser merged = adminUserRepository.save(obj);
        adminUserRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AdminUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdminUserIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to initialize correctly", dod.getRandomAdminUser());
        AdminUser obj = dod.getNewTransientAdminUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AdminUser' identifier to be null", obj.getId());
        adminUserRepository.save(obj);
        adminUserRepository.flush();
        Assert.assertNotNull("Expected 'AdminUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AdminUserIntegrationTest.testDelete() {
        AdminUser obj = dod.getRandomAdminUser();
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdminUser' failed to provide an identifier", id);
        obj = adminUserRepository.findOne(id);
        adminUserRepository.delete(obj);
        adminUserRepository.flush();
        Assert.assertNull("Failed to remove 'AdminUser' with identifier '" + id + "'", adminUserRepository.findOne(id));
    }
    
}
