// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.fnic.dhc.domain;

import cn.fnic.dhc.domain.AdminRoleDataOnDemand;
import cn.fnic.dhc.domain.AdminRoleIntegrationTest;
import cn.fnic.dhc.repository.AdminRoleRepository;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AdminRoleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AdminRoleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AdminRoleIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AdminRoleIntegrationTest: @Transactional;
    
    @Autowired
    AdminRoleDataOnDemand AdminRoleIntegrationTest.dod;
    
    @Autowired
    AdminRoleRepository AdminRoleIntegrationTest.adminRoleRepository;
    
    @Test
    public void AdminRoleIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to initialize correctly", dod.getRandomAdminRole());
        long count = adminRoleRepository.count();
        Assert.assertTrue("Counter for 'AdminRole' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AdminRoleIntegrationTest.testFind() {
        AdminRole obj = dod.getRandomAdminRole();
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to provide an identifier", id);
        obj = adminRoleRepository.findOne(id);
        Assert.assertNotNull("Find method for 'AdminRole' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AdminRole' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AdminRoleIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to initialize correctly", dod.getRandomAdminRole());
        long count = adminRoleRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'AdminRole', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AdminRole> result = adminRoleRepository.findAll();
        Assert.assertNotNull("Find all method for 'AdminRole' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AdminRole' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AdminRoleIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to initialize correctly", dod.getRandomAdminRole());
        long count = adminRoleRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AdminRole> result = adminRoleRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'AdminRole' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AdminRole' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AdminRoleIntegrationTest.testFlush() {
        AdminRole obj = dod.getRandomAdminRole();
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to provide an identifier", id);
        obj = adminRoleRepository.findOne(id);
        Assert.assertNotNull("Find method for 'AdminRole' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAdminRole(obj);
        Integer currentVersion = obj.getVersion();
        adminRoleRepository.flush();
        Assert.assertTrue("Version for 'AdminRole' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdminRoleIntegrationTest.testSaveUpdate() {
        AdminRole obj = dod.getRandomAdminRole();
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to provide an identifier", id);
        obj = adminRoleRepository.findOne(id);
        boolean modified =  dod.modifyAdminRole(obj);
        Integer currentVersion = obj.getVersion();
        AdminRole merged = adminRoleRepository.save(obj);
        adminRoleRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AdminRole' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AdminRoleIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to initialize correctly", dod.getRandomAdminRole());
        AdminRole obj = dod.getNewTransientAdminRole(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AdminRole' identifier to be null", obj.getId());
        adminRoleRepository.save(obj);
        adminRoleRepository.flush();
        Assert.assertNotNull("Expected 'AdminRole' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AdminRoleIntegrationTest.testDelete() {
        AdminRole obj = dod.getRandomAdminRole();
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AdminRole' failed to provide an identifier", id);
        obj = adminRoleRepository.findOne(id);
        adminRoleRepository.delete(obj);
        adminRoleRepository.flush();
        Assert.assertNull("Failed to remove 'AdminRole' with identifier '" + id + "'", adminRoleRepository.findOne(id));
    }
    
}
