// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package cn.fnic.dhc.domain;

import cn.fnic.dhc.domain.AdminRoleDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect AdminRoleDataOnDemand_Roo_Configurable {
    
    declare @type: AdminRoleDataOnDemand: @Configurable;
    
}
